In [1]:
import numpy as np

In [2]:
# Problem 1

A = np.array([[3, -1, 4],
              [1, 5, -9]])

B = np.array([[2, 6, -5, 3],
              [5, -8, 9, 7],
              [9, -3, -2, -3]])

AB = A @ B
print(AB)

[[ 37  14 -32 -10]
 [-54  -7  58  65]]


In [3]:
# Problem 2

def Cayley_Hamilton(matrix):
    '''input a matrix A, return -A**3 + 9*A**2 -15*A'''
    A = np.array(matrix)
    return -np.linalg.matrix_power(A, 3) + 9*A@A - 15*A 

A_list = [[3, 1, 4],
          [1, 5, 9],
          [-5, 3, 1]]

print(Cayley_Hamilton(A_list))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [4]:
# Problem 3

def problem_3():
    A = np.triu(np.ones((7, 7)))
    B = -np.tril(np.ones((7, 7))) + np.triu(np.full((7, 7), 5)) - 5 * np.eye(7)
    return np.int64(A @ B @ A)

print(problem_3())

[[ -7  -8  -3   8  25  48  77]
 [ -6 -12 -12  -6   6  24  48]
 [ -5 -10 -15 -14  -7   6  25]
 [ -4  -8 -12 -16 -14  -6   8]
 [ -3  -6  -9 -12 -15 -12  -3]
 [ -2  -4  -6  -8 -10 -12  -8]
 [ -1  -2  -3  -4  -5  -6  -7]]


In [5]:
# Problem 4

def problem_4(array):
    A = array.copy()
    A[A < 0] = 0
    return A

print(problem_4(np.array([-1, 2, 5, -45])))

[0 2 5 0]


In [6]:
# Problem 5

def problem_5():
    A = np.arange(6).reshape(3, 2).T
    B = np.tril(np.full((3,3),3))
    C = -2 * np.eye(3)
    I = np.ones((3,3))
    first_row = np.hstack((np.zeros(6).reshape((3,-1)), A.T, I))
    second_row = np.hstack((A, np.zeros((2, 4))))
    third_row = np.column_stack((B, np.zeros(3), C))
    return np.vstack((first_row, second_row, third_row))
    
print(problem_5())

[[ 0.  0.  0.  1.  1.  1.  1.]
 [ 0.  0.  2.  3.  1.  1.  1.]
 [ 0.  0.  4.  5.  1.  1.  1.]
 [ 0.  2.  4.  0.  0.  0.  0.]
 [ 1.  3.  5.  0.  0.  0.  0.]
 [ 3.  0.  0.  0. -2. -0. -0.]
 [ 3.  3.  0.  0. -0. -2. -0.]
 [ 3.  3.  3.  0. -0. -0. -2.]]


In [7]:
# Problem 6

def problem_6(matrix):
    '''input matrix, return row-stochastic matrix,
    matrix entries should be positive'''
    row_sum = matrix.sum(axis = 1)
    return matrix / row_sum.reshape((matrix.shape[0],1))

A_matrix = np.arange(20).reshape((4,5))

print(problem_6(A_matrix))

[[0.         0.1        0.2        0.3        0.4       ]
 [0.14285714 0.17142857 0.2        0.22857143 0.25714286]
 [0.16666667 0.18333333 0.2        0.21666667 0.23333333]
 [0.17647059 0.18823529 0.2        0.21176471 0.22352941]]


In [8]:
# Problem 7

def problem_7(grid):
    '''
    input grid, 
    return the greatest product of four adjacent numbers in the same direction'''
    right_max = np.max(grid[:, :-3] * grid[:, 1:-2] * grid[:, 2:-1] * grid[:, 3:])
    left_max = np.max(grid[:, 3:] * grid[:, 2:-1] * grid[:, 1:-2] * grid[:, :-3])
    down_max = np.max(grid[:-3, :] * grid[1:-2, :] * grid[2:-1, :] * grid[3:, :])
    up_max = np.max(grid[3:, :] * grid[2:-1, :] * grid[1:-2, :] * grid[:-3, :])
    right_diag_max = np.max(grid[:-3, :-3] * grid[1:-2, 1:-2] * grid[2:-1, 2:-1] * grid[3:, 3:])
    left_diag_max = np.max(grid[3:, 3:] * grid[2:-1, 2:-1] * grid[1:-2, 1:-2] * grid[:-3, :-3])
    
    return np.max((right_max, left_max, down_max, up_max, right_diag_max, left_diag_max))

grid = np.load('grid.npy')
print(problem_7(grid))

51267216
