In [2]:
import numpy as np
from scipy import optimize as optimize

In [39]:
# wage, rent, utility and derivative of utility

w = lambda b2, b3: (1-α) * A * ((b2 + b3)/2.2)**α
r = lambda b2, b3: α * A * (2.2/(b2 + b3))**(1-α) - δ
u = lambda c: (c**(1-σ) - 1) / (1 - σ)
uprime = lambda c: c**(-σ)

In [57]:
def feasible(f_params, bvec_guess):
    b_cnstr = np.full(2, False)
    c_cnstr = np.full(3, False)
    K_cnstr = np.full(1, False)
    
    # unpack parameters
    α, β, δ, α, A = f_params
    
    # unpack savings
    b2, b3 = bvec_guess
    
    wage = w(b2, b3)
    rent = r(b2, b3)
    
    c1 = wage - b2
    c2 = wage + (1 + rent) * b2 - b3
    c3 = 0.2 * wage + (1 + rent) * b3
    
    c = [c1, c2, c3]
    
    for i in range(3):
        if c[i] < 0:
            c_cnstr[i] = True
        else:
            c_cnstr[i] = False
            
    if c_cnstr[0] == True:
        b_cnstr[0] = True
    elif c_cnstr[1] == True:
        b_cnstr = [True, True]
    elif c_cnstr[2] == True:
        b_cnstr[1] = True
    
    if b2 + b3 > 0:
        K = [True]
    
    return b_cnstr, c_cnstr, K_cnstr

In [58]:
# parameters
β = 0.442
δ = 0.6415
σ = 3
A = 1
α = 0.35

f_params = α, β, δ, σ, A

In [59]:
feasible(f_params, [1.0, 1.2])

(array([ True, False]), array([ True, False, False]), array([False]))

Nonnegativity constraint of c1 is violated, likely to be caused by b2

In [60]:
feasible(f_params, [0.06, -0.001])

(array([False, False]), array([False, False, False]), array([False]))

No constraint is violated

In [61]:
feasible(f_params, [0.1, 0.1])

(array([False, False]), array([False, False, False]), array([False]))

No constraint is violated

In [ ]:
def eqbm(x):
    b2bar, b3bar = x
    f1 = β * (1 + r(b2bar, b3bar)) * uprime(w(b2bar, b3bar) + (1 + r(b2bar, b3bar)) * b2bar - b3bar)
    - uprime(w(b2bar, b3bar) - b2bar)
    f2 = β * (1 + r(b2bar, b3bar)) * uprime((1 + r(b2bar, b3bar)) * b3bar + 0.2 * w(b2bar, b3bar))
    - uprime(w(b2bar, b3bar) + (1 + r(b2bar, b3bar)) * b2bar - b3bar)
    return f1, f2

In [ ]:
def get_SS(params, bvec_guess, SS_graphs):
    

In [42]:
bool([0, 0, 1])

True